- name: Install prezto from git.
  become: yes
  become_user: guida
  git:
    repo: "{{ prezto_repo_url }}"
    dest: /home/guida/.zprezto
    track_submodules: yes
    force: yes
    update: no

- name: Symlink prezto files
  file:
    src: "/home/guida/.zprezto/runcoms/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
    force: true
    owner: "guida"
  with_items:
    - zlogout
    - zprofile
    - zshenv

- name: Install dotfiles
  file:
    src: "/home/guida/.dotfiles/{{ item }}"
    dest: "/home/guida/.{{ item }}"
    state: link
    force: true
    owner: "guida"
  with_items:
    - zpreztorc
    - zshrc

- name: Set permissions on ~/.zprezto.
  file:
    mode: "0755"
    path: "/home/guida/.zprezto"
    owner: "guida"

- name: Set zsh as the user shell
  user:
    name: "guida"
    shell: /usr/bin/zsh
