- name: Install prezto from git.
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ prezto_repo_url }}"
    dest: "/home/{{ user }}/.zprezto"
    track_submodules: yes
    force: yes
    update: no
    version: master

- name: Symlink prezto files
  file:
    src: "/home/{{ user }}/.zprezto/runcoms/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
    force: true
    owner: "{{ user }}"
  with_items:
    - zlogout
    - zprofile
    - zshenv

- name: Install dotfiles
  file:
    src: "/home/{{ user }}/.dotfiles/{{ item }}"
    dest: "/home/{{ user }}/.{{ item }}"
    state: link
    force: true
    owner: "{{ user }}"
  with_items:
    - zpreztorc
    - zshrc

- name: Set permissions on ~/.zprezto.
  file:
    mode: "0755"
    path: "/home/{{ user }}/.zprezto"
    owner: "{{ user }}"

- name: Set zsh as the user shell
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
