- name: Clone dotfiles repository
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ dot_files_repo }}"
    dest: "/home/{{ user }}/.dotfiles"
    force: yes
    update: yes
    version: master

- name: Install dotfiles
  become: yes
  become_user: "{{ user }}"
  file:
    src: "/home/{{ user }}/.dotfiles/{{ item }}"
    dest: "/home/{{ user }}/.{{ item }}"
    state: link
  with_items:
    - gemrc
    - vimrc
    - gitconfig
    - p10k.zsh