- name: Clone dotfiles repository
  become: yes
  become_user: guida
  git:
    repo: "{{ dot_files_repo }}"
    dest: "/home/guida/.dotfiles"
    force: yes
    update: yes

- name: Install dotfiles
  become: yes
  become_user: guida
  file:
    src: "/home/guida/.dotfiles/{{ item }}"
    dest: "/home/guida/.{{ item }}"
    state: link
  with_items:
    - gemrc
    - vimrc
    - gitconfig
    - p10k.zsh