---
- name: Add docker apt keys
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present

- name: Install docker
  become: yes
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: present

- name: Add user to docker group
  become: yes
  user:
    name: "{{ user }}"
    groups:
      - docker
    append: yes
