---
- name: Update system packages
  pacman:
    update-cache: yes
    upgrade: yes

- name: Install basic packages
  pacman:
    name: "{{ package }}"
    state: present
  vars:
    package:
      - base-devel
      - git
      - vim
      - zsh
      - curl
      - ca-certificates
      - htop
      - nodejs
      - yarn
      - keychain # to autoload ssh-keys
      - code # vscode
